import Head from "next/head";
import { FC } from "react";

interface ILayoutProps {
  title: string;
  children: JSX.Element | JSX.Element[];
}

export const Layout: FC<ILayoutProps> = ({ title, children }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{children}</main>
    </>
  );
};
